server:
  port: 9092
  servlet:
    context-path: /api

spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  zipkin:
    base-url: http://localhost:9411

zuul:
  routes:
    backend:
      path: /demo-backend/**
      url: http://localhost:32772/
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      backend:
      - limit: 10
        refresh-interval: 1
        type:
          - user
