server:
  port: 80
  servlet:
    context-path: /api

spring:
  application:
    name: gateway
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  zipkin:
    base-url: ${ZIPKIN_BASE_URL}

zuul:
  routes:
    backend:
      path: /demo-backend/**
      url: ${DEMO_BACKEND_SERVICE}
  ratelimit:
    enabled: ${RATE_LIMIT_ENABLED}
    repository: ${RATE_LIMIT_REPOSITORY}
    policy-list:
      backend:
      - limit: ${RATE_LIMIT}
        refresh-interval: ${RATE_LIMIT_REFRESH_INTERVAL}
        type:
          - user
